import type { Metadata } from "next";
import "./globals.css";
import NavBarp from "./Componentes/navbar/navbar";
import Rodape from "./Componentes/navbar/rodape";

export const metadata: Metadata = {
  title: "Nuvix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="pt-br">
        <body className="antialiased">
          <NavBarp />
          {children}
          <Rodape />
        </body>
      </html>
    </>
  );
}
