import type { Metadata } from "next";
import "./globals.css";
import NavBarp from "./comp/navbar/navbar";
import Rodape from "./Componentes/navbar/rodape";


export const metadata: Metadata = {
  title: "Nuvix",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   return (
    <>
    <html lang="pt-br">
      <NavBarp/>
      <body className="antialiased">
        {children}
      </body>
      <Rodape />
    </html>
    </>
  );
}
